Corrección script mpconnect

diff --git a/bin/mpconnect b/bin/mpconnect
--- a/bin/mpconnect
+++ b/bin/mpconnect
@@ -1,14 +1,11 @@
 #!/bin/bash
 
-invalid_input () {
-   echo "Invalid input." >&2
-   exit 1
-}
 
 read -p "Enter server Ip > " ip
 
-if [[ ! -z $ip  &&  $ip =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
+if [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
    echo "Ip válida."
 else
-   invalid_input
+   echo "Invalid input." >&2
+   exit 1
 fi
